### ISSUE TITLE
About STDC 

### ISSUE THREAD

**Issue by chris2000520** [zh320/realtime-semantic-segmentation-pytorch#11]
Have you used the pre-trained weights from the STDC official repository? If used, will mIoU be improved? 
Looking forward to your reply！

**Comment by zh320** [comment]
Hi Chris, 

The models in this repo are built from scratch followed only the guidances of their corresponding papers. Only those models whose backbones are ResNet or MobileNetV2 are using pretrained weights from torchvision. So it's likely we are unable to load the pretrained weights from official repo. However, it's possible to get better results if we pretrain the model using larger dataset. As you may see, the mIoUs of some models in this repo are lower than the official implementation, which may be due to pretraining.

Best.
