### ISSUE TITLE
LiteSeg model only has one concate but the model in paper has two

### ISSUE THREAD

**Issue by zhy168** [zh320/realtime-semantic-segmentation-pytorch#14]

**Comment by zh320** [comment]
Hi zhy,

There are two concatenate within the codes, one is in this line

https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/0e5fe540f13c91d36ec30e745dc151ad356d3fd4/models/liteseg.py#L39

The other one is inside the DASPPModule

https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/0e5fe540f13c91d36ec30e745dc151ad356d3fd4/models/liteseg.py#L72

Regarding the improvement of performance, it's probably due to tricks like train more epochs, more augmentations and using ema.

Best,

**Comment by zhy168** [comment]
Thanks a lot
